language: node_js
node_js:
  - "14.16.1"
dist: trusty
services:
  - mongodb
env:
  - PORT=3000
cache: 
  directories:
    - node_modules
install:
  - npm install
script:
  - nohup npm start &
  - sleep 3
  - npm test